### ISSUE TITLE
Make support for unsupported servers

### ISSUE THREAD

**Issue by ProtocolNebula** [zenflow/node-fast-download#12]
This is for developer, no for client:
If server doesn't support multipart, instead of crash (currently emit a wrong hard to catch error in a callback) script must download without resume support or at least warn to the code to handle with other manager.

**Comment by zenflow** [comment]
Sorry, just to be clear, what do you mean "doesn't support multipart"? Do you mean support of "partial requests"? Indicated by the [`Accept-Ranges` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges)?

**Comment by ProtocolNebula** [comment]
Sorry, I write this too much fast and at that moment I don't remember the name, but yes, `Range Request` was what I mean.

In the code, the error is instantiated and passed to a Callback, I make some test but can't avoid to show in the terminal and I'm not sure how to identify this kind of error, will be great if Error will pass an especific error number to avoid read the message error.

If necessary I can create a pull request solving this (if will be accepted).

**Comment by zenflow** [comment]
You could check `error.message`, e.g. `if (error.message === 'the server will not accept range requests') { ... }` but I do think an error code would be better, and a nice improvement.. I'll gladly accept a PR. 

Here is the relevant code:

https://github.com/zenflow/node-fast-download/blob/529ba57f6c72b655150f5bdcb59297f1ca63ecb2/lib/FastDownload.js#L110-L122

Note that the error is only made if the server doesn't accept range requests **and** the download isn't supposed to start at the start of the file (e.g. continuing an earlier download). If the server doesn't accept range requests and the download is supposed to start at the start of the file (and end at the end of the file) then we fall back to downloading with a single request. 

Also note that you can check `dl.headers['accept-ranges'] === 'bytes'` in the 'start' event, and call `dl.abort()` if you want.

**Comment by ProtocolNebula** [comment]
Thanks for info.

Maybe I will check this week, currently if server don't support ranges, this script crash, adding a setting to download anyways if fails is a good solution too.

**Comment by ProtocolNebula** [comment]
Pull request ready.

With this little fix this library should be easy to use, anyways I will try to use the recommended libraries in #11
